### ISSUE TITLE
Autosub

### ISSUE THREAD

**Issue by geyalfpl** [Sundfjord/fantasy#1]
How about auto sub mate? Look like this just about live point & bps, are you planning on it?

**Comment by Sundfjord** [comment]
Hi.
By auto sub, what exactly do you mean?

**Comment by geyalfpl** [comment]
David luiz case this gameweek, he dont play, so lets say i have doherty who will replace him in my starting lineup, i know it will be automatically update by FPL but it takes a few hours later (from last game in this gameweek)

**Comment by Sundfjord** [comment]
Yes, this will definitely be implemented at some point, has been on the to-do list from the beginning.

**Comment by geyalfpl** [comment]
Ah nice, just make sure you get my point, take a look at https://imgur.com/a/l6xe964 i'm talking about a part of bottom on the image

**Comment by Sundfjord** [comment]
This should be implemented with 050f4f308ba4a87022911dbb4155077171ed58e1, closing.
